[package]
name = "hippo"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
egui = "0.29.1"
env_logger = "0.11.5"
rfd = "0.14.1"
calamine = "0.25.0"
polars = { version = "0.42.0" ,features = ["lazy"] }
egui_plot = "0.29.0"
